---

- name: Debian | Install ipsumdump dependencies
  ansible.builtin.apt:
    name:
      - make
      - gcc
      - g++
      - ca-certificates
      - perl
      - patch
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  register: pkg_result
  until: pkg_result is success
- name: Redhat | Install ipsumdump dependencies
  ansible.builtin.yum:
    name:
      - make
      - gcc
      - gcc-c++
      - perl
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"
  register: pkg_result
  until: pkg_result is success

- name: Check if ipsumdump archive is present
  ansible.builtin.stat:
    path: "/root/ipsumdump-{{ ipsumdump_v }}.tar.gz"
  register: ipsumdumparchive

- name: Download ipsumdump archive
  ansible.builtin.get_url:
    url: "{{ ipsumdump_url }}"
    validate_certs: False
    dest: /root/ipsumdump-{{ ipsumdump_v }}.tar.gz
    mode: '0400'
    checksum: "sha256:{{ ipsumdump_archive_sha256 }}"
  when: not ipsumdumparchive.stat.exists

- name: Check if ipsumdump binary is present
  ansible.builtin.stat:
    path: "{{ ipsumdump_prefix }}/bin/ipsumdump"
  register: ipsumdumpbin

- name: Unarchive ipsumdump
  ansible.builtin.unarchive:
    remote_src: yes
    src: /root/ipsumdump-{{ ipsumdump_v }}.tar.gz
    mode: '0755'
    dest: /root
  when: not ipsumdumpbin.stat.exists

- name: Focal | patch SIOCGSTAMP for latest kernel headers
  ansible.posix.patch:
    src: patch-src-fromdevice.cc
    basedir: "/root/ipsumdump-{{ ipsumdump_v }}"
  when:
    - (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 20)
    - not ipsumdumpbin.stat.exists

- name: Compile and install ipsumdump
  ansible.builtin.command: "{{ item.command }}"
  args:
    chdir: "{{ item.chdir }}"
    creates: "{{ item.c }}"
  with_items:
    ## https://github.com/ansible/ansible/issues/8260
    - { command: './configure --prefix={{ ipsumdump_prefix }}',
        chdir: '/root/ipsumdump-{{ ipsumdump_v }}',
        c: '/root/ipsumdump-{{ ipsumdump_v }}/Makefile'
    }
    - { command: 'make',
        chdir: '/root/ipsumdump-{{ ipsumdump_v }}',
        c: '/root/ipsumdump-{{ ipsumdump_v }}/src/ipsumdump'
    }
    - { command: 'make install',
        chdir: '/root/ipsumdump-{{ ipsumdump_v }}',
        c: "{{ ipsumdump_prefix }}/bin/ipsumdump"
    }
  when: not ipsumdumpbin.stat.exists
