---

- name: Verify
  hosts: ipsumdump
  tasks:
    - name: Ensure /usr/local/bin/ipsumdump is present
      ansible.builtin.stat:
        path: /usr/local/bin/ipsumdump
      register: bin
    - name: Validate binary present
      ansible.builtin.assert:
        that: bin.stat.exists and bin.stat.size != 0 and bin.stat.mode == '0755'

    - name: Ensure binary is working
      ansible.builtin.command: /usr/local/bin/ipsumdump -h
      register: exec
      changed_when: false
      ignore_errors: true
    - name: Validate exec output
      ansible.builtin.assert:
        that: "'Usage: ipsumdump [DATA OPTIONS] [-i DEVNAMES | FILES] > SUMMARYFILE' in exec.stdout"
